#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDM_OPEN_PAR                            2
#define IDM_SAVEPAR                             4
#define IDM_SAVEIMAGE                           5
#define IDM_EXIT                                6
#define IDM_COPY                                7
#define IDM_FRACOPTIONS                         10
#define IDM_FRACTLOC                            11
#define IDC_FRACTYPE                            12
#define IDM_3DPARAM                             14
#define IDM_IMAGE_SIZE                          15
#define IDM_REALTIMEJULIA                       19
#define IDM_JULIA                               20
#define IDM_3D                                  21
#define IDM_RDS                                 25
#define IDM_STEREO                              26
#define IDM_TOGGLEPERT                          27
#define IDM_EDGE                                28
#define IDM_START                               30
#define IDM_THRESHOLD                           31
#define IDM_THRESH_OFF                          32
#define IDM_LOGVAL                              33
#define IDM_BIOMORPH                            34
#define IDM_DECOMP                              35
#define IDM_CYCLE                               36
#define IDM_BLKINDEX                            39
#define IDM_MAXCOL                              45
#define IDM_SLOPE                               50
#define IDC_MANDEL                              60
#define IDM_BAILOUT                             60
#define IDC_NEWTON                              61
#define IDC_CUBIC                               62
#define IDC_POWER                               63
#define IDC_GEO_NEWTON                          64
#define IDC_CIRCLE                              65
#define IDC_NEWTSPECIAL                         66
#define IDC_SIN                                 67
#define IDC_EXP                                 68
#define IDC_MATEIN                              69
#define IDC_RATMAP                              71
#define IDC_FIB                                 72
#define IDC_HENON                               73
#define IDC_BARNSLEYM1                          74
#define IDC_BARNSLEYM2                          75
#define IDC_BARNSLEYM3                          76
#define IDC_CELLULAR                            77
#define IDC_FROTH                               78
#define IDC_GINGER                              79
#define IDC_HOPALONG                            80
#define IDC_IFS                                 81
#define IDC_KAM                                 82
#define IDC_KAM3D                               83
#define IDC_MANOWAR                             84
#define IDC_LORENZ                              85
#define IDC_LORENZ3D1                           86
#define IDC_LORENZ3D2                           87
#define IDC_LORENZ3D3                           88
#define IDC_LORENZ3D4                           89
#define IDC_LSYSTEM                             90
#define IDC_LYAPUNOV                            91
#define IDC_MANDELAMBDA                         92
#define IDC_MANDELCLOUD                         93
#define IDC_MARTIN                              94
#define IDC_PICKOVER                            95
#define IDC_PLASMA                              96
#define IDC_ROSSLER                             97
#define IDC_SIERPINSKI                          98
#define IDC_SPIDERFP                            99
#define IDC_UNITY                               100
#define IDC_WALK                                101
#define IDC_FRACTPAR                            102
#define IDC_FORMULA                             103
#define IDC_FOURIER                             104
#define IDC_CMPLXNEWTON                         105
#define IDM_OPEN_TRUE_MAP                       105
#define IDC_SQRFN                               106
#define IDM_OPEN_PAL_MAP                        106
#define IDC_DIFFUSION                           107
#define IDM_SAVE_TRUE_MAP                       107
#define IDC_FNZXZ                               108
#define IDM_SAVE_PAL_MAP                        108
#define IDC_FNXFN                               109
#define IDI_ICON1                               109
#define IDC_FNPLUSFN                            110
#define IDM_SET_JULIA_SIZE                      110
#define IDC_TETRATE                             111
#define IDC_SQR1OVERFN                          112
#define IDM_UNDO                                112
#define IDC_DEGREE                              113
#define IDC_MANDELFN                            113
#define IDC_MANDELPHOENIX                       114
#define IDC_PHOENIX                             115
#define IDM_SETUPANIMATION                      115
#define IDC_MANDPHOENIXCMPLX                    116
#define IDM_OPEN_PNG                            116
#define IDC_FNZPLUSZ                            117
#define IDM_OPEN_SCI                            117
#define IDC_FNZPLUSFNPIX                        118
#define IDC_MANFNPLUSZSQRD                      119
#define IDC_MANFNPLUSEXP                        120
#define IDC_MANLAMFNORFN                        121
#define IDC_MANDELFNORFN                        122
#define IDM_PATHS                               122
#define IDC_ESCHER                              123
#define IDM_JULIA_ANIM                          123
#define IDC_VL                                  124
#define IDC_HYPERCOMPLEX                        125
#define IDM_STOPANIM                            126
#define IDM_EDITPAL                             127
#define IDM_PAUSEANIM                           129
#define IDC_STEWART                             130
#define IDC_QUADMAND                            131
#define IDM_FOURIERANIM                         131
#define IDC_VERHULST                            132
#define IDM_REDO                                132
#define IDC_LAMBDA                              133
#define IDC_ADDSINPI                            134
#define IDC_SETSINPI                            135
#define IDC_MAY                                 136
#define IDC_LINEAR                              140
#define IDC_LOG                                 141
#define IDC_SQUARE                              142
#define IDC_INVERSE                             143
#define IDC_SQUAREROOT                          144
#define IDC_FIBTIME                             146
#define IDC_FIBSPIRALCOUNT                      147
#define IDC_ADDSPIRAL                           148
#define IDC_XROTATE                             160
#define IDC_YROTATE                             161
#define IDC_ZROTATE                             162
#define IDC_XSCALE                              163
#define IDC_YSCALE                              164
#define IDC_ZSCALE                              165
#define IDM_COLOUR_PAL                          200
#define ID_FRACNAME                             200
#define IDC_RED1                                201
#define IDC_RED2                                202
#define IDC_RED3                                203
#define IDC_RED4                                204
#define IDC_RED5                                205
#define IDC_RED6                                206
#define IDC_RED7                                207
#define IDC_RED8                                208
#define IDC_RED9                                209
#define IDC_RED10                               210
#define IDC_RED11                               211
#define IDC_RED12                               212
#define IDC_RED13                               213
#define IDC_START_RED                           213
#define IDC_START_BLUE                          214
#define IDC_START_GREEN                         215
#define IDC_END_RED                             216
#define IDC_INC_GREEN                           216
#define IDC_END_GREEN                           217
#define IDC_INC_RED                             217
#define IDC_END_BLUE                            218
#define IDC_INC_BLUE                            218
#define IDC_RED18                               219
#define IDC_INVERT                              220
#define IDC_RED19                               221
#define IDC_RED20                               222
#define IDC_CYCLE_START                         223
#define IDC_STRETCH                             223
#define IDC_REDSCROLL                           230
#define IDC_GRNSCROLL                           231
#define IDC_BLUSCROLL                           232
#define IDC_RANDSCROLL                          233
#define IDC_RED                                 235
#define IDM_DEFAULTCOL                          237
#define IDC_RANDPAL                             238
#define IDC_RAND_DIV                            239
#define IDC_STARTITER                           240
#define IDC_STARTRGB                            241
#define IDC_ENDITER                             242
#define IDC_ENDRGB                              243
#define IDC_PLASMA_GRAIN                        265
#define IDM_LSYSTEM                             300
#define IDM_STEREOPAIRSETUP                     310
#define IDC_NO_INSIDE                           400
#define IDC_ZMAG                                401
#define IDC_BOF60                               402
#define IDC_BOF61                               403
#define IDC_HUE1                                500
#define IDC_HUE2                                501
#define IDC_HUE3                                502
#define IDM_SETINSIDE                           510
#define IDM_USEDEFAULTPALETTE                   520
#define IDC_NORMAL                              530
#define IDC_90DEGREES                           531
#define IDC_180DEGREES                          532
#define IDC_270DEGREES                          533
#define IDC_OTHER_DEGREES                       534
#define IDC_NO_OUTSIDE                          540
#define IDC_REAL1                               541
#define IDC_IMAG1                               542
#define IDC_SUM                                 543
#define IDC_MULT                                544
#define IDC_ATAN                                545
#define IDC_PERT1                               546
#define IDC_PERT2                               547
#define IDC_EPSCR                               552
#define IDC_STARTRAILS                          553
#define IDC_POTENTIAL                           556
#define IDC_TIERAZONFILTERS                     557
#define IDC_TIERAZONCOLOURS                     558
#define IDC_GUESS                               600
#define IDC_BOUNDARY                            601
#define IDC_TESSERAL                            602
#define IDC_1PASS                               603
#define IDC_2PASS                               604
#define IDC_VERTBLINDS                          605
#define IDC_HORBLINDS                           606
#define IDC_SPIRAL                              607
#define IDC_FWDDIFF                             608
#define IDC_COLOUR0                             1000
#define IDC_FULLSCREEN                          1000
#define IDC_HUE4                                1000
#define IDC_NEWTONFLOWER                        1000
#define IDC_NUMBERTHREADS                       1000
#define IDC_PALETTESHIFT1                       1000
#define IDC_RATE_START                          1000
#define IDC_SQUAREWAVE                          1000
#define IDC_XPERSPECTIVE                        1000
#define IDM_HELP                                1000
#define IDC_COLOUR1                             1001
#define IDC_COLOURINGLABEL                      1001
#define IDC_INITIALVALUE                        1001
#define IDC_KFR                                 1001
#define IDC_LYAPSEQ                             1001
#define IDC_ORBITS                              1001
#define IDC_SAWTOOTH                            1001
#define IDC_SPECIAL                             1001
#define IDC_STATUSINFO                          1001
#define IDC_TEDDY                               1001
#define IDC_THRESHOLD                           1001
#define IDC_WRITEPNGDIRECT                      1001
#define IDC_COLOUR2                             1002
#define IDC_COLOURINGOPTION                     1002
#define IDC_JULIAREAL                           1002
#define IDC_MPG                                 1002
#define IDC_NEWTONAPPLE                         1002
#define IDC_PAIRFLAG                            1002
#define IDC_SHOWTERRAIN                         1002
#define IDC_TRIANGLE                            1002
#define IDC_USE_MUTEX                           1002
#define IDC_WRITEMEMDIRECT                      1002
#define IDM_ABOUT                               1002
#define IDM_STALKS                              1002
#define IDC_BKGROUNDCOLOUR                      1003
#define IDC_COLOUR3                             1003
#define IDC_FULLWAVE                            1003
#define IDC_GIF                                 1003
#define IDC_HUE5                                1003
#define IDC_NEWTONMSET                          1003
#define IDC_ORBITS1                             1003
#define IDC_PARAM5                              1003
#define IDC_STEREODEPTH                         1003
#define IDC_WRITEMPEGDIRECT                     1003
#define ID_FRACPARTX13                          1003
#define IDC_COLOUR4                             1004
#define IDC_DIMTEXT                             1004
#define IDC_FRM                                 1004
#define IDC_HUE6                                1004
#define IDC_JULIAIMAG                           1004
#define IDC_RED21                               1004
#define IDC_SINWAVE                             1004
#define IDC_WRITEPNGFILELIST                    1004
#define IDM_TESSFILLCOL                         1004
#define IDC_COLOUR5                             1005
#define IDC_COSWAVE                             1005
#define IDC_DERIVATIVESLOPE                     1005
#define IDC_DIM_Z2                              1005
#define IDC_PALETTESHIFT                        1005
#define IDC_PLOTWIDTH                           1005
#define IDC_RATE_END                            1005
#define IDC_SCI                                 1005
#define IDC_SHOWAXES                            1005
#define IDC_TIERAZON                            1005
#define IDC_WRITEMPEGDIRECT1                    1005
#define IDC_COLOUR6                             1006
#define IDC_DIM_X                               1006
#define IDC_DISPLAYALLAXES                      1006
#define IDC_FWDDIFFSLOPE                        1006
#define IDC_INVERTRADIUS                        1006
#define IDC_ISJULIA                             1006
#define IDC_PARAM_NUM                           1006
#define IDC_THREADCREATIONDELAY                 1006
#define IDC_JULIAWIDTH                          1007
#define IDC_LINES                               1007
#define IDC_NOSLOPE                             1007
#define IDC_PARAM6                              1007
#define IDC_RADIUS                              1007
#define IDC_SPROTTMAPS                          1007
#define IDC_THREADCOMPLETIONDELAY               1007
#define IDC_USER_DATA                           1007
#define IDM_ROTDEG                              1007
#define IDC_DIM_Y                               1008
#define IDC_ICONS                               1008
#define IDC_RETURN                              1008
#define IDC_SHOWCENTRE                          1008
#define IDC_THREADENDINGDELAY                   1008
#define IDC_USERPATH                            1008
#define IDC_DIM_Z1                              1009
#define IDC_FFT                                 1009
#define IDC_INVERTFRACT                         1009
#define IDC_INVERTTEXT                          1009
#define IDC_THREADPERTDELAY                     1009
#define ID_SLOPETYPE                            1009
#define IDC_DIM_Z                               1010
#define IDC_ITER_DIV                            1010
#define IDC_MANZZPWR                            1010
#define IDC_MANZPOWER                           1011
#define IDC_NUMBERCORES                         1011
#define IDC_VERTBIAS                            1011
#define IDM_RADIUS                              1011
#define IDC_ITERATIONS                          1012
#define IDC_OSCILLATORS                         1012
#define IDC_PAL_OFFSET                          1012
#define IDM_CENTREX                             1012
#define IDC_NEWTONVARIATION                     1013
#define IDC_NUMDIM                              1013
#define IDM_CENTREY                             1013
#define ID_SLOPEANGLE                           1013
#define IDC_DIRECTFORMULA                       1014
#define IDC_ORBITCOL                            1014
#define IDC_YPERSPECTIVE                        1014
#define ID_SLOPERATIO                           1014
#define IDC_DISTEST                             1015
#define IDC_MALTHUS                             1015
#define IDC_ZPERSPECTIVE                        1015
#define ID_SLOPEPOWER                           1015
#define IDC_DISTESTWIDTH                        1016
#define IDC_GEOMETRICSHAPES                     1016
#define IDC_NUMVAR                              1016
#define IDC_PARAM7                              1016
#define IDC_POLYNOMIAL                          1017
#define IDC_XREFLECT                            1017
#define ID_STARTPALETTE                         1017
#define IDC_CURLICUES                           1018
#define IDC_INITIAL                             1018
#define IDC_CHUA                                1019
#define IDC_DT                                  1019
#define IDC_3_OR_6                              1020
#define IDC_BURNINGSHIPPOWER                    1020
#define IDC_YREFLECT                            1020
#define IDC_BURNINGSHIP                         1021
#define IDC_SHADING                             1021
#define IDC_YREFLECTLABEL                       1021
#define IDC_FRACTALMAPS                         1022
#define IDC_XREFLECTLABEL                       1022
#define IDC_INIT_STRING                         1023
#define IDC_THORN                               1023
#define IDC_WHITE_BACKGROUND                    1023
#define IDM_TYPE                                1023
#define IDC_AVERAGECENTRE                       1024
#define IDC_CELL_TYPE                           1024
#define IDC_ROTATIONANIM                        1024
#define IDC_SURFACES                            1024
#define IDM_SUBTYPE                             1024
#define IDC_KNOTS                               1025
#define IDC_START_ROW                           1025
#define IDM_TRANSFACTOR                         1025
#define IDC_BG_RED                              1026
#define IDC_BUDDHABROT                          1026
#define IDC_CELL_RULE                           1026
#define IDM_STARTPAL                            1026
#define IDC_TETRATION                           1027
#define IDM_BAILOUTTYPE                         1027
#define IDC_SLOPEDERIVATIVE                     1028
#define IDC_ZBIAS                               1028
#define IDM_LIGHTDIR                            1028
#define IDC_BG_GREEN                            1029
#define IDC_PERTURBATION                        1029
#define IDC_WALK_STEPSIZE                       1029
#define IDM_MAPDEPTH                            1029
#define IDC_SLOPEFWDDIFF                        1030
#define IDM_MAPSTRENGTH                         1030
#define IDC_LATOO                               1031
#define IDM_SLOPEDEGREE                         1031
#define IDC_TOWER                               1032
#define IDM_SLOPEERROR                          1032
#define IDC_ANT                                 1034
#define IDC_QUAT                                1035
#define IDC_DYNAMIC                             1036
#define IDC_X_SIZE                              1036
#define IDC_FRACTINTPOPCORN                     1037
#define IDC_Y_SIZE                              1037
#define IDC_HEIGHT                              1039
#define IDC_PIXEL                               1040
#define IDC_JULIALOC                            1041
#define IDC_ANIMPNG                             1042
#define IDC_SPEED                               1042
#define IDC_JULIA10                             1043
#define IDC_PNG                                 1043
#define IDC_THRESHOLD_START                     1043
#define IDC_COL                                 1044
#define IDC_JULIA8                              1044
#define IDC_THRESHOLD_END                       1044
#define IDC_JULIA6                              1045
#define IDC_SCRIPT_FILENAME                     1045
#define IDC_HOR                                 1046
#define IDC_JULIA4                              1046
#define IDC_LSYS                                1046
#define IDC_JULIA3                              1047
#define IDC_MAP                                 1047
#define IDC_VERT                                1047
#define IDC_PAR                                 1048
#define IDC_WIDTH                               1048
#define IDC_WIDTH_START                         1048
#define IDC_WIDTH_END                           1049
#define IDC_XCOORD                              1049
#define IDC_IFSD                                1050
#define IDC_SEQUENCE_NAME                       1050
#define IDC_FRAMES                              1051
#define IDC_ANIMSTART                           1052
#define IDC_STARTNOW                            1053
#define IDC_SHOWPALETTE                         1054
#define IDC_YCOORD                              1054
#define IDC_CENTRE                              1055
#define IDC_MANP                                1056
#define IDM_FRACTALCOORDS                       1056
#define IDC_START_X                             1057
#define IDC_START_Y                             1058
#define IDC_END_X                               1059
#define IDC_END_Y                               1060
#define IDC_LINEARJUL                           1062
#define IDC_CIRCULAR                            1063
#define IDC_CARDIOID                            1064
#define IDC_LABEL01                             1066
#define IDC_LABEL02                             1067
#define IDC_LABEL03                             1068
#define IDC_LABEL04                             1069
#define IDC_TESTCURVE                           1070
#define IDC_PARAM0                              1072
#define IDC_PARAM1                              1073
#define IDC_PARAM2                              1074
#define IDC_PARAM3                              1075
#define IDC_PARAM4                              1076
#define IDC_RANGE                               1079
#define IDC_STARTREDSCROLL                      1080
#define IDC_STARTGRNSCROLL                      1081
#define IDC_STARTBLUSCROLL                      1082
#define IDC_ENDREDSCROLL                        1083
#define IDC_ENDGRNSCROLL                        1084
#define IDC_ENDBLUSCROLL                        1085
#define IDC_GREY                                1087
#define IDC_REDGREEN                            1088
#define IDC_REDBLUE                             1089
#define IDC_ROTATE                              1090
#define IDC_GREENBLUE                           1091
#define IDC_REPEATPAL                           1092
#define IDC_ACCEPTENTRY                         1093
#define IDM_STEPS                               1095
#define IDC_HARMONICS                           1096
#define IDC_HALFWAVE                            1097
#define IDC_IMPULSETRAIN                        1099
#define IDC_SCROLLBAR1                          1101
#define IDC_SCROLLBAR2                          1102
#define IDC_SCROLLBAR3                          1103
#define IDC_SCROLLBAR4                          1104
#define IDC_SCROLLBAR5                          1105
#define IDC_SCROLLBAR6                          1106
#define IDC_SCROLLBAR7                          1107
#define IDC_SCROLLBAR8                          1108
#define IDC_SCROLLBAR9                          1109
#define IDC_SCROLLBAR10                         1110
#define IDC_SCROLLBAR11                         1111
#define IDC_SCROLLBAR12                         1112
#define IDC_SCROLLBAR13                         1113
#define IDC_SCROLLBAR14                         1114
#define IDC_SCROLLBAR15                         1115
#define IDC_SCROLLBAR16                         1116
#define IDC_SCROLLBAR17                         1117
#define IDC_SCROLLBAR18                         1118
#define IDC_SCROLLBAR19                         1119
#define IDC_SCROLLBAR20                         1120
#define IDC_SCROLLBAR21                         1121
#define IDC_SCROLLBAR22                         1122
#define IDC_SCROLLBAR23                         1123
#define IDC_SCROLLBAR24                         1124
#define IDC_SCROLLBAR25                         1125
#define IDC_SCROLLBAR26                         1126
#define IDC_SCROLLBAR27                         1127
#define IDC_SCROLLBAR28                         1128
#define IDC_SCROLLBAR29                         1129
#define IDC_SCROLLBAR30                         1130
#define IDC_SCROLLBAR31                         1131
#define IDC_SCROLLBAR32                         1132
#define IDC_LABEL1                              1151
#define IDC_LABEL2                              1152
#define IDC_LABEL3                              1153
#define IDC_LABEL4                              1154
#define IDC_LABEL5                              1155
#define IDC_LABEL6                              1156
#define IDC_LABEL7                              1157
#define IDC_LABEL8                              1158
#define IDC_LABEL9                              1159
#define IDC_LABEL10                             1160
#define IDC_LABEL11                             1161
#define IDC_LABEL12                             1162
#define IDC_LABEL13                             1163
#define IDC_LABEL14                             1164
#define IDC_LABEL15                             1165
#define IDC_LABEL16                             1166
#define IDC_LABEL17                             1167
#define IDC_LABEL18                             1168
#define IDC_LABEL19                             1169
#define IDC_LABEL20                             1170
#define IDC_LABEL21                             1171
#define IDC_LABEL22                             1172
#define IDC_LABEL23                             1173
#define IDC_LABEL24                             1174
#define IDC_LABEL25                             1175
#define IDC_LABEL26                             1176
#define IDC_LABEL27                             1177
#define IDC_LABEL28                             1178
#define IDC_LABEL29                             1179
#define IDC_LABEL30                             1180
#define IDC_LABEL31                             1181
#define IDC_LABEL32                             1182
#define IDC_FNLIST1                             1185
#define IDC_FNLIST2                             1187
#define IDC_BAILOUT                             1188
#define IDC_MAINTASPECT                         1189
#define IDC_BAIL_MOD                            1200
#define IDC_BAIL_REAL                           1201
#define IDC_BAIL_IMAG                           1202
#define IDC_BAIL_OR                             1203
#define IDC_BAIL_AND                            1204
#define IDC_MANH                                1205
#define IDC_MANR                                1206
#define ID_LISTTITLE                            2000
#define IDC_NEWTONCROSS                         2001
#define IDC_TALIS                               2005
#define IDC_NEWTONJULIANOVA                     2006
#define IDC_QUARTET1                            2010
#define IDC_QUARTET2                            2011
#define IDC_QUARTET3                            2012
#define IDC_NOVA                                2013
#define IDC_RAMONCOS                            2014
#define IDC_RAMONSIN                            2015
#define IDC_FORMULA05                           2016
#define IDC_QUAD                                2018
#define IDC_MOUNTAIN                            2020
#define IDC_MARKSMANDEL                         2021
#define IDC_MARKSMANDELPWR                      2022
#define IDC_CMPLXMARKSMAND                      2023
#define IDC_STRETCHPALETTE                      2025
#define IDC_EXPANDSTARCOLS                      2026
#define IDC_USEPALETTE                          2027
#define IDC_RGB                                 2028
#define IDC_HUE9                                2029
#define IDC_HUE10                               2030
#define IDC_RGBRED                              2031
#define IDC_RGBGREEN                            2032
#define IDC_RGBBLUE                             2033
#define IDC_TRIANGLES                           2034
#define IDC_CIRCLES                             2035
#define IDC_CROSSROADS                          2036
#define IDC_PASCAL                              2037
#define IDC_APOLLONIUS                          2038
#define IDC_APOLLONIUSIFS                       2039
#define IDC_SIERPINSKIFLOWERS                   2040
#define IDC_ZIGZAG                              2041
#define IDC_GARGOYLE                            2042
#define IDM_OPEN_LST                            3000
#define ID_FRACPARAM1                           3201
#define ID_FRACPARAM2                           3202
#define ID_FRACPARAM3                           3203
#define ID_FRACPARAM4                           3204
#define ID_FRACPARAM5                           3205
#define ID_FRACPARAM6                           3206
#define ID_FRACPARAM7                           3207
#define ID_FRACPARAM8                           3208
#define ID_FRACPARAM9                           3209
#define ID_FRACPARAM10                          3210
#define ID_FRACPARAM11                          3211
#define ID_FRACPARTX1                           3221
#define ID_FRACPARTX2                           3222
#define ID_FRACPARTX3                           3223
#define ID_FRACPARTX4                           3224
#define ID_FRACPARTX5                           3225
#define ID_FRACPARTX6                           3226
#define ID_FRACPARTX7                           3227
#define ID_FRACPARTX8                           3228
#define ID_FRACPARTX9                           3229
#define ID_FRACPARTX10                          3230
#define ID_FRACPARTX11                          3231
#define ID_FRACPARTX12                          3232
#define IDC_A                                   4000
#define IDC_B                                   4001
#define IDC_C                                   4002
#define IDC_D                                   4003
#define IDC_E                                   4004
#define IDC_F                                   4005
#define IDC_G                                   4006
#define IDC_H                                   4007
#define IDC_I                                   4008
#define IDC_J                                   4009
#define IDC_K                                   4010
#define IDC_L                                   4011
#define IDC_M                                   4012
#define IDC_N                                   4013
#define IDC_O                                   4014
#define IDC_P                                   4015
#define IDC_Q                                   4016
#define IDC_R                                   4017
#define IDC_S                                   4018
#define IDC_T                                   4019
#define IDC_U                                   4020
#define IDC_V                                   4021
#define IDC_W                                   4022
#define IDC_X                                   4023
#define IDC_Y                                   4024
#define IDC_Z                                   4025
#define IDC_FILLED                              4100
#define IDC_UNFILLED                            4101
#define IDC_3D                                  4102
#define IDC_EXPANDPALETTE                       5000
#define IDC_DEFAULTPALETTE                      5001
#define IDC_STAR                                5002
#define IDC_FILLPOLYGON                         5003
#define IDC_USER                                8888
#define IDC_MOVINGWAVE                          10000
#define IDC_PLOT_CIRCLES                        10001
#define IDC_FFT_REAL                            10002
#define IDC_FFT_IMAG                            10003
#define IDC_FFT_REALIMAG                        10004
#define IDC_FFT_POWER                           10005
#define IDC_MOUNTAINLEVEL                       10005
#define IDC_DOPERSPECTIVE                       34464
#define IDC_CURVES                              40000
#define IDC_FORMULAVALUE                        40000
#define IDC_MORPHDELAY                          40000
#define IDC_PROGRAMNAME                         40000
#define IDC_XAXIS                               40000
#define IDM_GENMPEGSTATS                        40000
#define IDC_YAXIS                               40001
#define IDM_FDOPTIONS                           40001
#define IDC_ZAXIS                               40002
#define IDM_DISPLAYLOC                          40002
#define IDM_GET_PIXEL_COLOUR                    40004
#define IDM_RDS_SPOTS                           40005
#define IDC_REDSHIFTRIDER                       40007
#define IDM_PARAM_ANIM                          40007
#define IDC_POPCORN                             40008
#define IDM_INVERSION_ANIM                      40008
#define IDM_OSCILLATOR_ANIMATION                40009
#define IDM_UPDATE_FRACTAL                      40010
#define IDC_MANDELDERIVATIVES                   40011
#define IDM_MORPHOSC                            40011
#define IDM_SETUPTHREADS                        40012
#define IDM_SAVE_PAR_AND_IMAGE                  40013
#define IDM_OPEN_KALLES                         40014
#define IDM_TOGGLE_DISPLAY_PALETTE              40015
#define IDM_SAVE_KALLES                         40016
#define IDC_CARTESIAN                           40020
#define IDC_SPHERICAL                           40021
#define IDC_CYLINDRICAL                         40022
#define IDC_PARABOLIC                           40023
#define IDC_PARABOLOIDAL                        40024
#define IDC_ELLIPTICAL                          40025
#define IDC_TOROIDAL                            40026
#define IDC_PROLATE_SPHEROIDAL                  40027
#define IDC_OBLATE_SPHEROIDAL                   40028
#define IDC_BISPHERICAL                         40029
#define IDC_CONICAL                             40030
#define IDC_BIPOLAR                             40031
#define ID_FRACVAR01                            40051
#define ID_FRACVAR02                            40052
#define ID_FRACVAR03                            40053
#define ID_FRACVAR04                            40054
#define ID_FRACVAR05                            40055
#define ID_FRACVAR06                            40056
#define ID_FRACVAR07                            40057
#define ID_FRACVAR08                            40058
#define ID_FRACVAR09                            40059
#define ID_FRACVAR10                            40060
#define ID_FRACVARTX01                          40061
#define ID_FRACVARTX02                          40062
#define ID_FRACVARTX03                          40063
#define ID_FRACVARTX04                          40064
#define ID_FRACVARTX05                          40065
#define ID_FRACVARTX06                          40066
#define ID_FRACVARTX07                          40067
#define ID_FRACVARTX08                          40068
#define ID_FRACVARTX09                          40069
#define ID_FRACVARTX10                          40070
#define IDC_KLEINIAN                            40080
#define IDC_BG_BLUE                             50000
#define IDC_TEST                                50000
#define IDC_QUADRUPTWO                          50001
#define IDC_THREEPLY                            50003
#define IDC_CHIP                                50005
