;========================================================================
; Configuration File for Paul's Fractals: © Paul de Leeuw 24/04/2012
;========================================================================
;
; Note the config lines must start at character 0 and are case sensitive
;
; Comments are started with a ; character
;
;
; Path for PNG files
PNGPath=PNG
; Path for GIF files
PNGPath=GIF
; Path for MPG files
PNGPath=MPG
; Path for PNG files from animation generator
ANIMPNGPath=AnimPNG
; Path for COL files
COLPath=COL
; Path for MAP files
MAPPath=MAP
; Path for SCI files
SCIPath=SCI
; Path for PAR files
PARPath=PAR
; Path for IFS files
IFSPath=IFS
; Path for Lsys files
LSYSPath=LSYS
; Path for Formula files
FRMPath=
;
; Do we want to zoom along the edge?
;
ZoomEdge=TRUE
;
