/*
    FUNCTIONS.CPP a module for the per pixel calculations of fractals. 
    
    Written in Microsoft Visual 'C++' by Paul de Leeuw.

    This program is written in "standard" C. Hardware dependant code
    (console drivers & serial I/O) is in separate machine libraries.
*/

#include <math.h>
#include "manp.h"
#include "fractype.h"
#include "Complex.h"
#include "pixel.h"
#include "FunctionTemplate.h"
#include "BailoutTemplate.h"

/**************************************************************************
	Initialise functions for each pixel
**************************************************************************/

int	CPixel::InitFunctions(WORD type, Complex *z, Complex *q)
    {
    switch (type)
	{
	case MANDELFP:					// Mandelbrot
	case MANDEL:					// to handle fractint par files
	case JULIA:					// to handle fractint par files
	case JULIAFP:					// like he said
/**************************************************************************
    Run thorn type fractals
    Written by Paul Bourke
    Fractal attributed to Andrew Wayne Graff, alternatively named the "Secant Sea"
    Contribution by Dane Vandeputte
    Original: May 2004, Updated: May 2012
    Sample C source code -- Contribution by Adam Majewski
    This fractal is created by iterating the functions (xn,yn) and shading each pixel (x0,y0)
    depending on whether or how fast the series escapes to infinity.
    The parameter (cx,cy) is gives (slightly) different fractal images.
**************************************************************************/
	case THORN:					// Thorn Fractal
/**************************************************************************
    The Burning Ship fractal, first described and created by Michael Michelitsch and Otto E. Rössler in 1992, is generated by iterating the function
    in the complex plane which will either escape or remain bounded. The difference between this calculation and that for the Mandelbrot set is
    that the real and imaginary components are set to their respective absolute values before squaring at each iteration. The mapping is non-analytic
    because its real and imaginary parts do not obey the Cauchy–Riemann equations.
***************************************************************************/
	case BURNINGSHIP:				// Burning Ship
	    Init_Basic<Complex>(z, q, param, juliaflag, sqr, real_imag);
	    break;
/**************************************************************************
    The Burning Ship fractal for Higher Powers
    The function that is iterated to generate this fractal can be generalized
    to any arbitrary power:
	z = [|Re(z)| + i |Im(z)|]N + c
    As with the Mandelbrot set, this creates shapes that resemble the original
    shape but have increasingly many attached arms or buds. Below is a table
    showing the first few of these.
    With N=2 we get the Burning Ship. The N=3 version has been called the "Bird of Prey."

    The odd powers are symmetric around an axes that are oriented at +/- 45 degrees.
    This is probably due to the symmetry of the absolute value functions. This
    property has been mentioned at this site (external link) back in 1999.

    These images are all centered at (0,0) in the complex number plane, and all
    have a size of 5 horizontally and 4 vertically. This size is a bit too big
    and results in a lot of blank space in the images, but the N=2 fractal is
    offset from the origin, so the larger size is needed to have all the images
    drawn with a consistent location and size so they can be compared accurately.

    Here are a few images of the Cubic Burning Ship. The "bug" images are named
    because they look like actual bugs, not because of a software error! These
    are the first deep zoom images ever published of the cubic Burning Ship fractal.
    The left image size is 1.0e-19, and the right image is 1.0e-23.
    http://www.hpdz.net/StillImages/BurningShip.htm
	***************************************************************************/
	case BURNINGSHIPPOWER:				// Burning Ship to higher power
	case POWER:					// Power
	case JULIA4FP:
	case JULIA4:
	case MANDEL4FP:
	case MANDEL4:
	    Init_Power<Complex>(type, z, q, param, juliaflag, degree);
	    break;

	case CUBIC:					// Art Matrix Cubic
	    Init_Cubic<Complex>(z, q, param, juliaflag,	subtype, special, a, b, a2, aa3, t2, t3, temp, v);
	    break;

	case SPECIALNEWT:				// Art Matrix Newton
	    Init_SPECIALNEWT<Complex>(z, q, a, b, lm5, lp5);
	    break;

	case MATEIN:					// Art Matriuc Matein fractal
	    {
	    period_level = FALSE;			// no periodicity checking
	    int ret = Init_MATEIN<Complex, double>(z, q, param, juliaflag, oz, temp, distance, absolute);
	    if (ret < 0)
		return ret;   // propagate rejection
	    break;
	    }

	case SINFRACTAL:				// Sine
	    Init_SINFRACTAL<Complex>(z, q, param, juliaflag);
	    break;

	case REDSHIFTRIDER:				// RedShiftRider    a*z^2 +/- z^n + c
	    Init_REDSHIFTRIDER<Complex>(z, q, param, juliaflag, a, degree);
	    break;

	case TALIS:					// Talis Power    Z = Z^N/(M + Z^(N-1)) + C
	    Init_TALIS<Complex>(z, q, param, juliaflag, degree);
	    break;

	case POLYNOMIAL:				// Polynomial
	    Init_POLYNOMIAL<Complex>(z, q, param, juliaflag);

	    // keep this outside template
	    for (int i = 0; i < MAXPOLYDEG; i++)
		{
		if (param[2 + i] != 0.0)
		    {
		    fractalspecific[type].SlopeDegree = MAXPOLYDEG - i;
		    break;
		    }
		}
	    break;

	case RATIONALMAP:				// Art Matrix Rational Map 
	    {
	    // -----------------------------------
	    // 1. CONTROL LOGIC (CPixel responsibility)
	    // -----------------------------------

	    switch ((int)param[0])
		{
		case 0: subtype = 'A'; break;
		case 1: subtype = 'B'; break;
		default: subtype = 'A'; break;
		}
	    special = ((int)param[1] < 0) ? 0 : (int)param[1];

	    // threshold / palette logic stays here
	    if (threshold != OldThreshold)
		{
		OldThreshold = threshold;
		int gap = threshold / 16;			// split the colour map into 16 equal parts
		for (int i = 0; i < 4; i++)
		    {
		    penp[i] = penpref[i] * gap;
		    penn[i] = pennref[i] * gap;
		    }
		}

	    // -----------------------------------
	    // 2. PURE MATH (TEMPLATE CALL)
	    // -----------------------------------

	    int ret = Init_RATIONALMAP<Complex, double>(z, q, param, juliaflag,	subtype, a, b, alpha, temp, temp1, temp3);

	    if (ret < 0)
		return ret;

	    // -----------------------------------
	    // 3. POST-MATH STATE (CPixel responsibility)
	    // -----------------------------------

	    // escape + epsilon
	    if (alpha.x != 0.0 || alpha.y != 0.0)
		escape = 16.0 / alpha.CSumSqr();
	    else
		return(FALSE);				// no naughty division
	    epsilon = 0.000001 / escape;		// EPSILN = 0.000001/ESCAPE 

	    der = 1.0;					// DER = 1.0 
	    }
	    break;

	case MANDELDERIVATIVES:				// a group of Mandelbrot Derivatives
	    InitManDerFunctions(subtype, z, q);
	    break;

	case TIERAZON:					// a group of Tierazon fractals
	    InitTierazonFunctions(subtype, z, q);
	    break;

	case NEWTONAPPLE:				// a specific Tierazon fractal
	    InitTierazonFunctions(55, z, q);
	    break;

	case NEWTONFLOWER:				// a specific Tierazon fractal
	    InitTierazonFunctions(35, z, q);
	    break;

	case NEWTONMSET:				// a specific Tierazon fractal
	    InitTierazonFunctions(52, z, q);
	    break;

	case NEWTONPOLYGON:				// a specific Tierazon fractal
	    InitTierazonFunctions(31, z, q);
	    break;

	case NEWTONCROSS:				// a specific Tierazon fractal
	    InitTierazonFunctions(59, z, q);
	    break;

	case NEWTONJULIANOVA:				// a specific Tierazon fractal
	    InitTierazonFunctions(2, z, q);
	    break;

	case NEWTONVARIATION:				// a specific Tierazon fractal
	    InitTierazonFunctions(87, z, q);
	    break;

	case QUARTET1:					// a specific Tierazon fractal
	    InitTierazonFunctions(83, z, q);
	    break;

	case QUARTET2:					// a specific Tierazon fractal
	    InitTierazonFunctions(85, z, q);
	    break;

	case QUARTET3:					// a specific Tierazon fractal
	    InitTierazonFunctions(96, z, q);
	    break;

	case NOVA:
	    InitTierazonFunctions(2, z, q);
	    break;

	case QUAD:					// a specific Tierazon fractal
	    InitTierazonFunctions(90, z, q);
	    break;

	case RAMONSIN:					// a specific Tierazon fractal
	    InitTierazonFunctions(116, z, q);
	    break;

	case RAMONCOS:					// a specific Tierazon fractal
	    InitTierazonFunctions(117, z, q);
	    break;

	case FORMULA05:					// a specific Tierazon fractal
	    InitTierazonFunctions(5, z, q);
	    break;

	case TEDDY:					// a specific Tierazon fractal
	    InitTierazonFunctions(104, z, q);
	    break;

/*
#define NEWTONFLOWER		186
#define NEWTONMSET		190
#define NEWTONPOLYGON		174
#define NEWTONCROSS		193
#define NEWTONJULIANOVA		191
#define NEWTONVARIATION		207	
#define QUARTET1		194
#define QUARTET2		195
#define QUARTET3		196
#define NOVA			208	
#define QUAD			201
#define RAMONSIN		197
#define RAMONCOS		198
#define FORMULA05		199
#define TALIS			192
#define TEDDY			189

*/
	case TETRATION:					// a Paul Bourke fractal
	    InitTetration(z, q);
	    break;

	case KLEINIAN:					// a Paul Bourke fractal
	    InitKleinian(z, q);
	    break;
	}

    return 0;
    }

/**************************************************************************
	Run functions for each iteration
**************************************************************************/

int	CPixel::RunFunctions(WORD type, Complex *z, Complex *q, BYTE *SpecialFlag, long *iteration)
    {
    switch (type)
	{
	case MANDELFP:					// Mandelbrot
	case MANDEL:					// to handle fractint par files
	case JULIA:					// to handle fractint par files
	case JULIAFP:					// like he said
	case POWER:					// Power
	case JULIA4FP:
	case JULIA4:
	case MANDEL4FP:
	case MANDEL4:
	case BURNINGSHIP:				// Burning Ship
	case BURNINGSHIPPOWER:				// Burning Ship to higher power
	case CUBIC:					// Art Matrix Cubic
	    return FunctionsDispatch<Complex, double, WORD>(this, type, z, q, degree, sqr, real_imag, a, a2, aa3, b, v,
		temp, param, SpecialFlag, iteration, special, subtype, BailoutTestType, rqlim);

	case SPECIALNEWT:				// Art Matrix Newton
	    return Iter_SPECIALNEWT<Complex>(
		z, q, a, b, lm5, lp5, v, param, phaseflag, special);

	case MATEIN:					// Art Matriuc Matein fractal
	    return Iter_MATEIN<Complex>(z, q, oz, temp, distance, absolute, param, epsilon, escape, phaseflag);

	case SINFRACTAL:				// Sine
	    return Iter_SINFRACTAL<Complex>(this, z, q, param, BailoutTestType, rqlim);

	case EXPFRACTAL:				// Exponential
	    return Iter_EXP_FRACTAL<Complex>(z, q, param, degree, subtype, rqlim);

	case THORN:					// Thorn Fractal (Small and difficult to template - leave it as it is.
	    {
	    double a1 = z->x;
	    double b1 = z->y;
	    z->x = a1 / cos(b1) + q->x;
	    z->y = b1 / sin(a1) + q->y;
	    return DoBailout(BailoutTestType, z, rqlim);
	    }

	case REDSHIFTRIDER:				// RedShiftRider    a*z^2 +/- z^n + c
	    return Iter_REDSHIFTRIDER<Complex, double>(this, z, q, a, param, degree, BailoutTestType, rqlim);

	case TALIS:					// Talis Power    Z = Z^N/(M + Z^(N-1)) + C
	    return Iter_TALIS<Complex>(this, z, q, a, param, degree, BailoutTestType, rqlim);

	case POLYNOMIAL:				// Polynomial
	    return Iter_POLYNOMIAL<Complex>(this, z, q, param, BailoutTestType, rqlim);

	case RATIONALMAP:				// Art Matrix Rational Map
	    return Iter_RATIONALMAP<Complex, double>(this, z, q, a, b, param, der, escape, epsilon,
		iteration, threshold, special, alpha, &color);

	case MANDELDERIVATIVES:				// a group of Mandelbrot Derivatives
	    return (RunManDerFunctions(subtype, z, q, SpecialFlag, iteration));

	case TIERAZON:					// a group of Tierazon fractalsa
	    return (RunTierazonFunctions(subtype, z, q, SpecialFlag, iteration));

	case NEWTONAPPLE:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(55, z, q, SpecialFlag, iteration));

	case NEWTONFLOWER:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(35, z, q, SpecialFlag, iteration));

	case NEWTONMSET:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(52, z, q, SpecialFlag, iteration));

	case NEWTONPOLYGON:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(31, z, q, SpecialFlag, iteration));

	case NEWTONCROSS:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(59, z, q, SpecialFlag, iteration));

	case NEWTONJULIANOVA:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(2, z, q, SpecialFlag, iteration));

	case NEWTONVARIATION:				// a specific Tierazon fractal
	    return (RunTierazonFunctions(87, z, q, SpecialFlag, iteration));

	case QUARTET1:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(83, z, q, SpecialFlag, iteration));

	case QUARTET2:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(85, z, q, SpecialFlag, iteration));

	case QUARTET3:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(96, z, q, SpecialFlag, iteration));

	case NOVA:
	    return (RunTierazonFunctions(2, z, q, SpecialFlag, iteration));

	case QUAD:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(90, z, q, SpecialFlag, iteration));

	case RAMONSIN:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(116, z, q, SpecialFlag, iteration));

	case RAMONCOS:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(117, z, q, SpecialFlag, iteration));

	case FORMULA05:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(5, z, q, SpecialFlag, iteration));

	case TEDDY:					// a specific Tierazon fractal
	    return (RunTierazonFunctions(104, z, q, SpecialFlag, iteration));

	case TETRATION:					// Tetration fractal
	    return(DoTetration(iteration));
	    break;

	case KLEINIAN:					// Kleinian fractal
	    return (CalculateKleinian(z));
	    break;

	}
    return 0;
    }


