/*------------------------------------------
   SVG.CPP -- SVG File Write Functions
  ------------------------------------------*/

#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <vector>
#include "manpwin.h"
#include "Dib.h"
#include "colour.h"
#include "OtherFunctions.h"
#include "Hailstone.h"

extern	CDib		Dib;
extern	CTrueCol	TrueCol;
extern	int		xdots, ydots;
extern	long		threshold;
extern	double		hor, vert, mandel_width;
extern	char		*FractData(void);
extern	WORD		type;
extern	int		subtype;
extern	double		param[];
extern	double		iterations;
extern  COtherFunctions* g_pOtherFunctions;

/**************************************************************************
	Write SVG File with Metadata
	Based on the format from Numerical Visualizations
**************************************************************************/

int	write_svg_file(HWND hwnd, char *outfile, char *szAppName, char *CommentText)
{
    FILE	*fp = NULL;
    char	s[480];
    time_t	current_time;
    struct tm	*time_info;
    char	time_buffer[80];
    static HCURSOR	hCursor;
//    BYTE	*pixels;
//    int		x, y;
//    RGBTRIPLE	rgb;

    hCursor = LoadCursor((HINSTANCE)NULL, IDC_WAIT);
    SetCursor(hCursor);

    // Open file for writing
    if ((fp = fopen(outfile, "w")) == NULL)
    {
        hCursor = LoadCursor((HINSTANCE)NULL, IDC_ARROW);
        SetCursor(hCursor);
        wsprintf(s, "SVG can't open output file: %s", outfile);
        MessageBox(hwnd, s, szAppName, MB_ICONEXCLAMATION | MB_OK);
        MessageBeep(0);
        return -1;
    }

    // Get current time for metadata
    time(&current_time);
    time_info = localtime(&current_time);
    strftime(time_buffer, sizeof(time_buffer), "%Y-%m-%dT%H:%M:%S", time_info);

    // Write SVG header with viewBox in pixel coordinates
    // Using viewBox with preserveAspectRatio for responsive scaling
    // The viewBox defines the coordinate system (pixels), while the SVG scales to fit
    fprintf(fp, "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
    fprintf(fp, "<svg viewBox=\"0 0 %d %d\"\n", xdots, ydots);
    fprintf(fp, "     preserveAspectRatio=\"xMidYMid meet\"\n");
    fprintf(fp, "     style=\"max-width: 100%%; height: auto;\"\n");
    fprintf(fp, "     xmlns=\"http://www.w3.org/2000/svg\" version=\"1.1\">\n");
    fprintf(fp, "  <!-- ========================================= -->\n");
    fprintf(fp, "  <!-- ManpWIN Metadata                         -->\n");
    fprintf(fp, "  <!-- ========================================= -->\n");
    fprintf(fp, "  <title>Hailstone Sequence Visualization</title>\n");
    fprintf(fp, "  <desc>2D visualization of Collatz-inspired dynamics generated by ManpWIN</desc>\n");
    fprintf(fp, "\n");

    // Write RDF metadata
    fprintf(fp, "  <metadata>\n");
    fprintf(fp, "    <rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n");
    fprintf(fp, "             xmlns:dc=\"http://purl.org/dc/elements/1.1/\">\n");
    fprintf(fp, "      <rdf:Description>\n");
    fprintf(fp, "        <dc:title>Hailstone Sequence Visualization</dc:title>\n");
    fprintf(fp, "        <dc:creator>ManpWIN64</dc:creator>\n");
    fprintf(fp, "        <dc:date>%s</dc:date>\n", time_buffer);
    fprintf(fp, "        <dc:format>image/svg+xml</dc:format>\n");
    fprintf(fp, "        <dc:description>Exported from ManpWIN fractal application</dc:description>\n");
    fprintf(fp, "      </rdf:Description>\n");
    fprintf(fp, "    </rdf:RDF>\n");
    fprintf(fp, "  </metadata>\n");
    fprintf(fp, "\n");

    // Write application-specific metadata
    fprintf(fp, "  <!-- Application-Specific Metadata for Reproducibility -->\n");
    fprintf(fp, "  <g id=\"visualization-parameters\" style=\"display:none;\">\n");
    fprintf(fp, "    <desc>\n");
    fprintf(fp, "      Visualization Type: Hailstone Sequence\n");
    fprintf(fp, "      Software: ManpWIN64\n");
    fprintf(fp, "      Export Date: %s\n", time_buffer);
    fprintf(fp, "      Resolution: %dx%d pixels\n", xdots, ydots);
    fprintf(fp, "\n");
    fprintf(fp, "      Algorithm Parameters:\n");
    fprintf(fp, "        MaxIterations: %ld\n", (long)iterations);
    fprintf(fp, "        Type: %d\n", type);
    fprintf(fp, "        Subtype: %d\n", subtype);
    
    // Write parameters if available
    fprintf(fp, "        Parameters:\n");
    for (int i = 0; i < 10; i++)
    {
        if (param[i] != 0.0)
            fprintf(fp, "          param[%d]: %.10g\n", i, param[i]);
    }
    fprintf(fp, "\n");
    
    fprintf(fp, "      Color Mapping:\n");
    fprintf(fp, "        Palette: %ld colors\n", threshold);
    fprintf(fp, "        Method: Iteration-based coloring\n");
    fprintf(fp, "\n");
    
    fprintf(fp, "      Coordinate System:\n");
    fprintf(fp, "        Center X: %.10g\n", hor);
    fprintf(fp, "        Center Y: %.10g\n", vert);
    fprintf(fp, "        Width: %.10g\n", mandel_width);
    fprintf(fp, "\n");
    fprintf(fp, "      ViewBox (pixel coordinates for SVG rendering):\n");
    fprintf(fp, "        minX: 0\n");
    fprintf(fp, "        minY: 0\n");
    fprintf(fp, "        width: %d\n", xdots);
    fprintf(fp, "        height: %d\n", ydots);

    // Add Hailstone-specific information if this is a Hailstone fractal
    if (type == HAILSTONE)
    {
        if (g_pOtherFunctions && g_pOtherFunctions->pHailstone)
        {
            const HailstoneConfig& config = g_pOtherFunctions->pHailstone->GetConfig();
            const CycleInfo& cycleInfo = g_pOtherFunctions->pHailstone->GetCycleInfo();
            const std::vector<HailstonePoint>& points = g_pOtherFunctions->pHailstone->GetPoints();

            fprintf(fp, "\n");
            fprintf(fp, "      Hailstone Sequence Information:\n");
            fprintf(fp, "        Starting Point: (%d, %d)\n", config.startX, config.startY);
            fprintf(fp, "        Total Iterations: %d\n", (int)points.size());
            fprintf(fp, "        Max Iterations: %d\n", config.maxIterations);

            if (cycleInfo.detected)
            {
                fprintf(fp, "        Cycle Detected: YES\n");
                fprintf(fp, "          Cycle Point: (%d, %d)\n", cycleInfo.x, cycleInfo.y);
                fprintf(fp, "          First Seen: Step %d\n", cycleInfo.startStep);
                fprintf(fp, "          Repeated At: Step %d\n", cycleInfo.endStep);
                fprintf(fp, "          Cycle Length: %d\n", cycleInfo.length);
            }
            else
            {
                fprintf(fp, "        Cycle Detected: NO (stopped at max iterations)\n");
            }

            fprintf(fp, "        Display Options:\n");
            fprintf(fp, "          Show Axes: %s\n", config.showAxes ? "Yes" : "No");
            fprintf(fp, "          Show Point Labels: %s\n", config.showPointLabels ? "Yes" : "No");
            fprintf(fp, "          Show Dots: %s\n", config.showDots ? "Yes" : "No");
        }
    }

    fprintf(fp, "    </desc>\n");
    fprintf(fp, "  </g>\n");
    fprintf(fp, "\n");

    // Write visualization graphics
    fprintf(fp, "  <!-- Visualization Graphics -->\n");
    fprintf(fp, "  <rect width=\"100%%\" height=\"100%%\" fill=\"black\"/>\n");
    fprintf(fp, "\n");

    /*
    // Get pixel data from DIB and write as SVG
    pixels = Dib.DibPixels.data();
    if (pixels != NULL)
    {
        // Write pixels as small rectangles
        // For performance, we could group consecutive pixels of the same color
        for (y = 0; y < ydots; y++)
        {
            for (x = 0; x < xdots; x++)
            {
                int offset = (y * xdots + x);
                BYTE colorIndex = pixels[offset];

                // Get RGB color from palette
                if (colorIndex < threshold && colorIndex < MAXPALETTE)
                {
                    rgb = TrueCol.PalettePtr[colorIndex];

                    // Only write non-black pixels to keep file size reasonable
                    if (rgb.rgbtRed != 0 || rgb.rgbtGreen != 0 || rgb.rgbtBlue != 0)
                    {
                        fprintf(fp, "  <rect x=\"%d\" y=\"%d\" width=\"1\" height=\"1\" fill=\"rgb(%d,%d,%d)\"/>\n",
                                x, y, rgb.rgbtRed, rgb.rgbtGreen, rgb.rgbtBlue);
                    }
                }
            }
        }
    }
    */

    // --- Hailstone Vector Rendering ---
    if (type == HAILSTONE && g_pOtherFunctions->pHailstone)
	{
	const auto& points = g_pOtherFunctions->pHailstone->GetPoints();
	const auto& cycleInfo = g_pOtherFunctions->pHailstone->GetCycleInfo();
	const HailstoneConfig& config = g_pOtherFunctions->pHailstone->GetConfig();

	if (points.size() > 1)
	    {
	    // --- Calculate bounds ---
	    double minX = points[0].x, maxX = points[0].x;
	    double minY = points[0].y, maxY = points[0].y;
	    double dotRadius = config.dotSize * (xdots + ydots) * 0.25;

	    // Clamp ONCE
	    if (dotRadius < 1.5) dotRadius = 1.5;
	    if (dotRadius > 6.0) dotRadius = 6.0;

	    for (const auto& pt : points)
		{
		if (pt.x < minX) minX = pt.x;
		if (pt.x > maxX) maxX = pt.x;
		if (pt.y < minY) minY = pt.y;
		if (pt.y > maxY) maxY = pt.y;
		}

	    double rangeX = maxX - minX;
	    double rangeY = maxY - minY;
	    if (rangeX < 1e-12) rangeX = 1.0;
	    if (rangeY < 1e-12) rangeY = 1.0;

	    // Add padding (nice visual spacing)
	    double padX = rangeX * 0.1;
	    double padY = rangeY * 0.1;

	    minX -= padX; maxX += padX;
	    minY -= padY; maxY += padY;

	    rangeX = maxX - minX;
	    rangeY = maxY - minY;

	    // --- Mapping lambdas ---
	    auto mapX = [&](double x)
		{
		return (x - minX) * xdots / rangeX;
		};

	    auto mapY = [&](double y)
		{
		return ydots - ((y - minY) * ydots / rangeY); // flip Y
		};

	    fprintf(fp, "  <g id=\"hailstone\" fill=\"none\" stroke-linecap=\"round\">\n");

	    fprintf(fp, "  <g id=\"summary\" font-family=\"monospace\" font-size=\"14\" fill=\"yellow\">\n");

	    int yText = 20;
	    int lineStep = 18;

	    fprintf(fp, "    <text x=\"10\" y=\"%d\">Hailstone Sequence (N,X,Y)</text>\n", yText);
	    yText += lineStep;

	    fprintf(fp, "    <text x=\"10\" y=\"%d\">Starting point: (%d, %d)</text>\n",
		yText, config.startX, config.startY);
	    yText += lineStep;

	    fprintf(fp, "    <text x=\"10\" y=\"%d\">Total points: %d</text>\n",
		yText, (int)points.size());
	    yText += lineStep;


	    if (cycleInfo.detected)
		{
		const auto& cp = points[cycleInfo.startStep];

		fprintf(fp,
		    "    <text x=\"10\" y=\"%d\">Cycle Detected: Point (%d, %d, %d)</text>\n",
		    yText,
		    cycleInfo.startStep,
		    (int)cp.x,
		    (int)cp.y);

		yText += lineStep;

		fprintf(fp,
		    "    <text x=\"10\" y=\"%d\">Cycle length: %d</text>\n",
		    yText,
		    cycleInfo.endStep - cycleInfo.startStep);

		yText += lineStep;
		}

	    fprintf(fp, "  </g>\n");

	    double zeroX = mapX(0.0);
	    double zeroY = mapY(0.0);

	    if (config.showAxes)
		{
		fprintf(fp, "  <g id=\"axes\" stroke=\"gray\" stroke-width=\"1\">\n");

		// X axis
		if (minY <= 0 && maxY >= 0)
		    {
		    fprintf(fp,
			"<line x1=\"0\" y1=\"%.2f\" x2=\"%d\" y2=\"%.2f\" />\n",
			zeroY, xdots, zeroY);
		    }

		// Y axis
		if (minX <= 0 && maxX >= 0)
		    {
		    fprintf(fp,
			"<line x1=\"%.2f\" y1=\"0\" x2=\"%.2f\" y2=\"%d\" />\n",
			zeroX, zeroX, ydots);
		    }

		fprintf(fp, "  </g>\n");
		fprintf(fp, "  <g id=\"ticks\" stroke=\"gray\" stroke-width=\"1\">\n");

		// X-axis ticks
		if (minY <= 0 && maxY >= 0)
		    {
		    int tickStart = (int)ceil(minX);
		    int tickEnd = (int)floor(maxX);

		    for (int tick = tickStart; tick <= tickEnd; tick++)
			{
			if (tick == 0) continue;

			double sx = mapX((double)tick);

			fprintf(fp,
			    "<line x1=\"%.2f\" y1=\"%.2f\" x2=\"%.2f\" y2=\"%.2f\" />\n",
			    sx, zeroY - 3,
			    sx, zeroY + 3);
			}
		    }

		// Y-axis ticks
		if (minX <= 0 && maxX >= 0)
		    {
		    int tickStart = (int)ceil(minY);
		    int tickEnd = (int)floor(maxY);

		    for (int tick = tickStart; tick <= tickEnd; tick++)
			{
			if (tick == 0) continue;

			double sy = mapY((double)tick);

			fprintf(fp,
			    "<line x1=\"%.2f\" y1=\"%.2f\" x2=\"%.2f\" y2=\"%.2f\" />\n",
			    zeroX - 3, sy,
			    zeroX + 3, sy);
			}
		    }

		fprintf(fp, "  </g>\n");
		}

	    // --- Draw FIRST point ---
	    const auto& p0 = points[0];

	    RGBTRIPLE rgb0 = TrueCol.PalettePtr[threshold / 2];

	    if (config.showDots)
		{
		fprintf(fp,
		    "<circle cx=\"%.3f\" cy=\"%.3f\" r=\"%.2f\" fill=\"rgb(%d,%d,%d)\" />\n",
		    mapX(p0.x), mapY(p0.y),
		    dotRadius,
		    rgb0.rgbtRed, rgb0.rgbtGreen, rgb0.rgbtBlue);
		}

	    if (config.showPointLabels)
		{
		fprintf(fp,
		    "<text x=\"%.3f\" y=\"%.3f\" font-size=\"10\" fill=\"white\">(%d, %d, %d)</text>\n",
		    mapX(p0.x) + 3,
		    mapY(p0.y) - 3,
		    0,
		    (int)p0.x,
		    (int)p0.y);
		}

	    for (size_t i = 0; i + 1 < points.size(); i++)
		{
		const auto& p1 = points[i];
		const auto& p2 = points[i + 1];

		bool isCycle = cycleInfo.detected &&
		    (int)i >= cycleInfo.startStep &&
		    (int)i < cycleInfo.endStep;

		int colorIndex = isCycle ? (threshold * 3 / 4) : (threshold / 2);
		if (colorIndex >= MAXPALETTE) colorIndex = MAXPALETTE - 1;

		RGBTRIPLE rgb = TrueCol.PalettePtr[colorIndex];

		double zeroX = mapX(0.0);
		double zeroY = mapY(0.0);

		fprintf(fp,
		    "    <line x1=\"%.3f\" y1=\"%.3f\" x2=\"%.3f\" y2=\"%.3f\" "
		    "stroke=\"rgb(%d,%d,%d)\" stroke-width=\"1\"/>\n",
		    mapX(p1.x), mapY(p1.y),
		    mapX(p2.x), mapY(p2.y),
		    rgb.rgbtRed, rgb.rgbtGreen, rgb.rgbtBlue);

		if (config.showDots)
		    {
		    fprintf(fp,
			"<circle cx=\"%.3f\" cy=\"%.3f\" r=\"%.2f\" fill=\"rgb(%d,%d,%d)\" />\n",
			mapX(p2.x), mapY(p2.y),
			dotRadius,
			rgb.rgbtRed, rgb.rgbtGreen, rgb.rgbtBlue);
		    }

		if (config.showPointLabels)
		    {
		    fprintf(fp,
			"    <text x=\"%.3f\" y=\"%.3f\" font-size=\"10\" fill=\"white\">(%d, %d, %d)</text>\n",
			mapX(p2.x) + 3,
			mapY(p2.y) - 3,
			(int)(i+1), p2.x, p2.y);
			}
		    }

/*


	    // --- Final point (dot + label) ---
	    const auto& pLast = points.back();

	    RGBTRIPLE rgb = TrueCol.PalettePtr[threshold / 2];

	    // Dot
	    if (config.showDots)
		{
		fprintf(fp,
		    "<circle cx=\"%.3f\" cy=\"%.3f\" r=\"%.2f\" fill=\"rgb(%d,%d,%d)\" />\n",
		    mapX(pLast.x), mapY(pLast.y),
		    dotRadius,
		    rgb.rgbtRed, rgb.rgbtGreen, rgb.rgbtBlue);
		}

	    // Label
	    if (config.showPointLabels)
		{
		fprintf(fp,
		    "<text x=\"%.3f\" y=\"%.3f\" font-size=\"10\" fill=\"white\">(%d, %d, %d)</text>\n",
		    mapX(pLast.x) + 4,
		    mapY(pLast.y) - 4,
		    (int)(points.size() - 1),
		    (int)pLast.x,
		    (int)pLast.y);
		}
*/


	    fprintf(fp, "  </g>\n");
	    }
	}


    // Close SVG
    fprintf(fp, "</svg>\n");
    fclose(fp);

    hCursor = LoadCursor((HINSTANCE)NULL, IDC_ARROW);
    SetCursor(hCursor);

    return 0;
}
